"""
Run this script once after training to generate weights.h for Vitis HLS.
The header embeds W1, b1, W2, b2 as static const ROM arrays so the FPGA
never has to read them from DDR during inference.
"""
import numpy as np
import os

WORKDIR = os.path.dirname(os.path.abspath(__file__))

def fmt_row(row):
    return ', '.join(f'{v:.8e}f' for v in row)

def array1d_to_c(name, arr):
    vals = fmt_row(arr)
    return f'static const float {name}[{len(arr)}] = {{\n    {vals}\n}};\n'

def array2d_to_c(name, arr):
    rows = []
    for i, row in enumerate(arr):
        rows.append(f'    /* row {i:2d} */ {{ {fmt_row(row)} }}')
    body = ',\n'.join(rows)
    r, c = arr.shape
    return f'static const float {name}[{r}][{c}] = {{\n{body}\n}};\n'

print('Loading weights...', end=' ')
W1 = np.load(os.path.join(WORKDIR, 'W1.npy')).astype(np.float32)
b1 = np.load(os.path.join(WORKDIR, 'b1.npy')).astype(np.float32)
W2 = np.load(os.path.join(WORKDIR, 'W2.npy')).astype(np.float32)
b2 = np.load(os.path.join(WORKDIR, 'b2.npy')).astype(np.float32)
print(f'W1={W1.shape}  b1={b1.shape}  W2={W2.shape}  b2={b2.shape}')

out_path = os.path.join(WORKDIR, 'weights.h')
with open(out_path, 'w') as f:
    f.write('#ifndef WEIGHTS_H\n')
    f.write('#define WEIGHTS_H\n\n')
    f.write('// Auto-generated by export_weights_header.py — do not edit manually.\n')
    f.write('// Arrays declared static const so HLS synthesises them as BRAM ROMs.\n\n')
    f.write(array2d_to_c('W1', W1))
    f.write('\n')
    f.write(array1d_to_c('b1', b1))
    f.write('\n')
    f.write(array2d_to_c('W2', W2))
    f.write('\n')
    f.write(array1d_to_c('b2', b2))
    f.write('\n#endif // WEIGHTS_H\n')

size_kb = os.path.getsize(out_path) / 1024
print(f'Written: weights.h  ({size_kb:.0f} KB)')
